local insert = require("mimosa.insert")

describe("insert", function()
  describe("format_tag", function()
    it("formats markdown tag for markdown filetype", function()
      assert.equals("![](images/diagram.svg)", insert.format_tag("images/diagram.svg", "markdown"))
    end)

    it("formats markdown tag for quarto filetype", function()
      assert.equals("![](images/diagram.svg)", insert.format_tag("images/diagram.svg", "quarto"))
    end)

    it("formats html tag for html filetype", function()
      assert.equals('<img src="images/photo.png">', insert.format_tag("images/photo.png", "html"))
    end)

    it("falls back to markdown for unknown filetype", function()
      assert.equals("![](file.svg)", insert.format_tag("file.svg", "text"))
    end)

    it("falls back to markdown for nil filetype", function()
      assert.equals("![](file.svg)", insert.format_tag("file.svg", nil))
    end)

    it("falls back to markdown for empty filetype", function()
      assert.equals("![](file.svg)", insert.format_tag("file.svg", ""))
    end)
  end)

  describe("resolve_path", function()
    it("appends extension when not present", function()
      local path, err = insert.resolve_path("images/diagram", "svg")
      assert.equals("images/diagram.svg", path)
      assert.is_nil(err)
    end)

    it("does not double extension when already present", function()
      local path, err = insert.resolve_path("images/diagram.svg", "svg")
      assert.equals("images/diagram.svg", path)
      assert.is_nil(err)
    end)

    it("appends extension when path has different extension", function()
      local path, err = insert.resolve_path("images/diagram.png", "svg")
      assert.equals("images/diagram.png.svg", path)
      assert.is_nil(err)
    end)

    it("returns nil for empty input", function()
      local path, err = insert.resolve_path("", "svg")
      assert.is_nil(path)
      assert.is_nil(err)
    end)

    it("returns nil for nil input", function()
      local path, err = insert.resolve_path(nil, "svg")
      assert.is_nil(path)
      assert.is_nil(err)
    end)

    it("validates absolute path with existing parent", function()
      local path, err = insert.resolve_path("/tmp/test-file", "svg")
      assert.equals("/tmp/test-file.svg", path)
      assert.is_nil(err)
    end)

    it("rejects absolute path with missing parent", function()
      local path, err = insert.resolve_path("/nonexistent-dir-xyz/file", "svg")
      assert.is_nil(path)
      assert.is_not_nil(err)
      assert.is_truthy(err:find("directory does not exist"))
    end)
  end)
end)
